name: Update README

on:
  push:
    paths:
      - 'src/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Debug files
      run: |
        echo "Repository contents:"
        ls -R
        echo "Solutions directories:"
        find src/ -type d

    - name: Update README
      run: |
        python3 .github/scripts/update_readme.py
        echo "README diff:"
        git diff README.md

    - name: Commit changes
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add README.md
        git diff --quiet && exit 0 || {
          git commit -m "Auto-update README"
          git push
        }
