name: Update README with new LeetCode problems

on:
  push:
    branches: [main]
    paths:
      - "src/**" # Trigger when files in solutions directory change

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for git diff

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Find new problem directories
        id: find-problems
        run: |
          # Get list of changed directories in src/
          DIRS=$(git diff --name-only --diff-filter=AD origin/main | grep -E '^src/[^/]+/' | cut -d/ -f1-2 | sort | uniq)
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT

      - name: Update README.md
        if: steps.find-problems.outputs.dirs != ''
        run: |
          # Install required Python packages
          python -m pip install --upgrade pip
          pip install pyyaml

          # Run script to update README
          python .github/scripts/update_readme.py

          # Commit changes if README was modified
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "docs: Update README with new problems" || echo "No changes to commit"
          git push
